### ISSUE TITLE
Character info request fail

### ISSUE THREAD

**Issue by neontflame** [drizzle-mizzle/CharacterAI_Discord_Bot#1]
Bot seems to be unable to request character info from character.ai upon ".set character [char id]" command

![request fail](https://user-images.githubusercontent.com/76576101/208027647-2ff97cd7-9f91-4730-b81f-f680a4371925.png)
![request fail 2](https://user-images.githubusercontent.com/76576101/208028030-648fb491-1323-4158-91ac-3940fd183fc8.PNG)

**Comment by drizzle-mizzle** [comment]
Servers were down for some time. Download last update and try again.

**Comment by neontflame** [comment]
nvm problem fixed. ran it in a linux vm
